name    'puppet-redmine'
version '0.0.1'
source  'https://github.com/leoc/puppet-redmine'
author  'Arthur Leonard Andersen'
license 'GPLv3'
summary 'Puppet Redmine Module'
description 'Module to install Redmine using puppet'
project_page 'https://github.com/leoc/puppet-redmine/'
